In [1]:
import sys
import os

sys.path.append(os.path.abspath(".."))

In [2]:
from src.utils.connect_mysql import Connect_MySQL

In [3]:

conn = Connect_MySQL(db='ecommerce',password='vighnesh')

In [4]:
dataframes = conn.fetch_tables_to_dfs(['orders','order_payments','customers','geolocation','order_items','products','sellers'])

Successfully fetch table sellers with 3095 rows.

In [5]:
orders_df = dataframes['orders']
order_payments_df = dataframes['order_payments']
customers_df = dataframes['customers']
geolocation_df = dataframes['geolocation']
order_items_df = dataframes['order_items']
products_df = dataframes['products']
sellers_df = dataframes['sellers']

In [6]:

order_reviews_df = conn.fetch_tables_to_dfs(['order_reviews'])
order_reviews_df = order_reviews_df['order_reviews']

Successfully fetch table order_reviews with 98410 rows.

In [7]:
dataframes.keys()

dict_keys(['orders', 'order_payments', 'customers', 'geolocation', 'order_items', 'products', 'sellers'])

In [8]:
customers_df.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,00012a2ce6f8dcda20d059ce98491703,248ffe10d632bebe4f7267f1f44844c9,6273,osasco,SP
1,000161a058600d5901f007fab4c27140,b0015e09bb4b6e47c52844fab5fb6638,35550,itapecerica,MG
2,0001fd6190edaaf884bcaf3d49edf079,94b11d37cd61cb2994a194d11f89682b,29830,nova venecia,ES
3,0002414f95344307404f0ace7a26f1d5,4893ad4ea28b2c5b3ddf4e82e79db9e6,39664,mendonca,MG
4,000379cdec625522490c315e70c7a9fb,0b83f73b19c2019e182fd552c048a22c,4841,sao paulo,SP

In [9]:
customers_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  str
 1   customer_unique_id        99441 non-null  str
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  str
 4   customer_state            99441 non-null  str
dtypes: int64(1), str(4)
memory usage: 3.8 MB

#### orders table

In [10]:
orders_df = conn.fetch_tables_to_dfs(['orders'])
orders_df = orders_df['orders']

Successfully fetch table orders with 99441 rows.

In [11]:
orders_df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,00010242fe8c5a6d1ba2dd792cb16214,3ce436f183e68e07877b285a838db11a,delivered,2017-09-13 08:59:02,2017-09-13 09:45:35,2017-09-19 18:34:16,2017-09-20 23:43:48,2017-09-29
1,00018f77f2f0320c557190d7a144bdd3,f6dd3ec061db4e3987629fe6b26e5cce,delivered,2017-04-26 10:53:06,2017-04-26 11:05:13,2017-05-04 14:35:00,2017-05-12 16:04:24,2017-05-15
2,000229ec398224ef6ca0657da4fc703e,6489ae5e4333f3693df5ad4372dab6d3,delivered,2018-01-14 14:33:31,2018-01-14 14:48:30,2018-01-16 12:36:48,2018-01-22 13:19:16,2018-02-05
3,00024acbcdf0a6daa1e931b038114c75,d4eb9395c8c0431ee92fce09860c5a06,delivered,2018-08-08 10:00:35,2018-08-08 10:10:18,2018-08-10 13:28:00,2018-08-14 13:32:39,2018-08-20
4,00042b26cf59d7ce69dfabb4e55b4fd9,58dbd0b2d70206bf40e62cd34e84d795,delivered,2017-02-04 13:57:51,2017-02-04 14:10:13,2017-02-16 09:46:09,2017-03-01 16:42:31,2017-03-17

In [12]:
order_reviews_df.loc[~order_reviews_df['review_comment_message'].isna(),['review_score','review_comment_message']].count()

review_score              40668
review_comment_message    40668
dtype: int64

In [13]:
order_reviews_df.count()

review_id                  98410
order_id                   98410
review_score               98410
review_comment_title       11519
review_comment_message     40668
review_creation_date       98410
review_answer_timestamp    98410
dtype: int64

In [14]:
orders_df[['order_purchase_timestamp','order_delivered_customer_date','order_estimated_delivery_date']].head()

,order_purchase_timestamp,order_delivered_customer_date,order_estimated_delivery_date
0,2017-09-13 08:59:02,2017-09-20 23:43:48,2017-09-29
1,2017-04-26 10:53:06,2017-05-12 16:04:24,2017-05-15
2,2018-01-14 14:33:31,2018-01-22 13:19:16,2018-02-05
3,2018-08-08 10:00:35,2018-08-14 13:32:39,2018-08-20
4,2017-02-04 13:57:51,2017-03-01 16:42:31,2017-03-17

In [15]:
orders_df.iloc[87464:87465]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
87464,e0e86ba567043fd48c98fbb535105f00,bdc1016dc15e2f13ee18d8f987b7f3c8,delivered,2018-06-24 18:25:51,2018-06-24 18:55:38,2018-06-25 09:07:00,2018-06-29 13:28:38,2018-07-17

In [16]:
customers_df

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,00012a2ce6f8dcda20d059ce98491703,248ffe10d632bebe4f7267f1f44844c9,6273,osasco,SP
1,000161a058600d5901f007fab4c27140,b0015e09bb4b6e47c52844fab5fb6638,35550,itapecerica,MG
2,0001fd6190edaaf884bcaf3d49edf079,94b11d37cd61cb2994a194d11f89682b,29830,nova venecia,ES
3,0002414f95344307404f0ace7a26f1d5,4893ad4ea28b2c5b3ddf4e82e79db9e6,39664,mendonca,MG
4,000379cdec625522490c315e70c7a9fb,0b83f73b19c2019e182fd552c048a22c,4841,sao paulo,SP
...,...,...,...,...,...
99436,fffecc9f79fd8c764f843e9951b11341,e5794df8573fa179a90a7b797fc4b71f,95630,parobe,RS
99437,fffeda5b6d849fbd39689bb92087f431,afbb5a642107cf6bb1ca68e863175f03,22461,rio de janeiro,RJ
99438,ffff42319e9b2d713724ae527742af25,680213db6ebd9e4f24d03280cbe10346,6754,taboao da serra,SP
99439,ffffa3172527f765de70084a7e53aae8,48fd7dec70f2b104a1d5e8c5c639102b,37130,alfenas,MG
99440,ffffe8b65bbe3087b653a978c870db99,736e6bfa0510aa5b878881a226a5fd89,6172,osasco,SP